### ISSUE TITLE
A part of conditional expression is always false/true

### ISSUE THREAD

**Issue by thehlopster** [RoseKavalier/H3API#1]
copy of https://github.com/RoseKavalier/H3Plugins/issues/9 https://github.com/RoseKavalier/H3API/blob/48b391a6b300c3684d6919be98a8078ce176213b/include/h3api/H3Dialogs/H3Dialogs.cpp#L1399-L1401
https://github.com/RoseKavalier/H3API/blob/48b391a6b300c3684d6919be98a8078ce176213b/include/h3api/H3String/H3String.cpp#L430-L432
https://github.com/RoseKavalier/H3API/blob/48b391a6b300c3684d6919be98a8078ce176213b/include/h3api/H3String/H3String.cpp#L437-L439
since `UINT` is `unsigned` it is never lower than 0, so this checks is unnecessary and can be removed

**Comment by RoseKavalier** [comment]
Merged request.
